# Udemy - Python para Data Science e Machine Learning

This doc will be used to register all steps of this course.

# Introduction to NumPy

The first step to work with NumPy objects and methods is import the module. Usually users import the module as 'np'.

In [8]:
import numpy as np

In [9]:
test = [1,2,3]

In [4]:
np.array(test)

array([1, 2, 3])

In [6]:
print(type(np.array(test)))

<class 'numpy.ndarray'>


In [10]:
test1 = [[1,2,3],[1,2,3],[1,2,3]]

In [11]:
np.array(test1)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [12]:
print(test1)

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]


In [15]:
np.array(test1)[0,1]

2

In [16]:
np.zeros((5,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [18]:
np.zeros((5,5,5))[0,0,0]

0.0

In [24]:
test3 = np.zeros((5,5,5))

In [25]:
print(test3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [26]:
test3[0,0,0] = 1

In [27]:
print(test3)

[[[1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [34]:
A = np.array([[1,1],[1,-1]])

In [35]:
A_inv = np.linalg.inv(A)

In [36]:
B = np.array([7,1])

In [37]:
B

array([7, 1])

In [38]:
A_inv

array([[ 0.5,  0.5],
       [ 0.5, -0.5]])

In [39]:
x = A_inv*B

In [40]:
x

array([[ 3.5,  0.5],
       [ 3.5, -0.5]])

In [43]:
x = np.dot(A_inv,B)

In [44]:
x

array([4., 3.])

In [45]:
x.shape

(2,)

In [46]:
teste = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

In [49]:
teste = np.array(teste)

In [50]:
teste

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
bol = teste%2==0

In [52]:
bol

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [53]:
teste_1 = teste[bol]

In [54]:
teste_1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [55]:
teste_1*2

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [56]:
teste

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [57]:
teste_1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [58]:
teste_2 =  teste_1*2

In [59]:
teste_2

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [60]:
teste[bol] = teste_2

In [61]:
teste

array([ 1,  4,  3,  8,  5, 12,  7, 16,  9, 20, 11, 24, 13, 28, 15, 32, 17,
       36, 19, 40])

In [62]:
teste = [1,2,3,4,5]

In [64]:
teste = np.array(teste,teste,teste)

ValueError: only 2 non-keyword arguments accepted

In [65]:
teste = [teste,teste,teste]

In [66]:
teste = np.array(teste)

In [67]:
teste

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [68]:
somente_primeira_coluna = teste[0,:]

In [69]:
somente_primeira_coluna

array([1, 2, 3, 4, 5])

In [70]:
somente_primeira_coluna = teste[:,0]

In [71]:
somente_primeira_coluna

array([1, 1, 1])

In [72]:
teste.shape

(3, 5)

In [74]:
identidade = np.eye(teste.shape[0], teste.shape[1])

In [75]:
identidade

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [77]:
identidade = identidade ==1

In [78]:
identidade

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [79]:
teste[identidade]

array([1, 2, 3])

In [80]:
teste*identidade

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0]])

# Introdução ao Pandas

Pandas é uma biblioteca baseada na numpy, permite visualização rápida e limpeza de dados.
- É semelhante ao excel.
- É possivel trabalhar com diversos tipos de dados.
- Possui métodos próprios de visualização.

In [82]:
import numpy as np
import pandas as pd

In [83]:
labels = ['a','b','c']

In [84]:
minha_lista = [10,20,30]

In [85]:
arr = np.array(minha_lista)

In [95]:
d = {'a':10,'b':20,'c':30}

Similar a estrutura de dicionário do python mas com certeza deve ter mais vantagens.

In [93]:
series = pd.Series(data=minha_lista,index=labels)

In [94]:
print(series['a'])

10


In [96]:
serie_1 = pd.Series([1,2,3,4], ['Rio de Janeiro','Minas Gerais','Sao Paulo', 'Pernambuco'])

In [98]:
serie_1

Rio de Janeiro    1
Minas Gerais      2
Sao Paulo         3
Pernambuco        4
dtype: int64

In [99]:
serie_2 = pd.Series([1,2,3,4], ['Rio de Janeiro','Minas Gerais','Sao Paulo', 'Amazonas'])

In [100]:
serie_1 + serie_2

Amazonas          NaN
Minas Gerais      4.0
Pernambuco        NaN
Rio de Janeiro    2.0
Sao Paulo         6.0
dtype: float64

## DataFrame - Criação e Fatiamento

In [101]:
import pandas as pd
import numpy as np

In [104]:
np.random.seed(101)

In [108]:
df = pd.DataFrame(np.random.randn(5,4),index = 'A B C D E'.split(), columns = 'W X Y Z'.split())

In [109]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [110]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [113]:
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [114]:
df['new'] = df['W'] + df['X']

In [115]:
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [116]:
df.drop('new', axis=1,inplace=True)

In [117]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [118]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [119]:
df.iloc[0,0]

2.706849839399938

In [120]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [121]:
df >

SyntaxError: invalid syntax (<ipython-input-121-65f0a705de85>, line 1)

In [122]:
df > 0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

# DataFrame - Seleção Condicional, set_index

Assim como em numpy, posso submeter meu dataframe a um condicional gerando um novo dataframe contendo booleanos (True e False). Com isso posso utilizar este dataframe booleano como indice do dataframe original obtendo um dataframe somente com os elementos que satisfizerem o condicional. No caso do numpy, retornava um array somente com os elementos que satisfaziam o condicional, no caso do dataframe, retorna uma matriz de mesmo tamanho, subtituindo os elementos que não satisfazem o condicional por Nan.

In [123]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [126]:
bol = df > 0

In [127]:
df[bol]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

Outra funcionalidade importante, posso utilizar o condicional aplicado em uma determinada coluna e com isso retornar apenas os valores da coluna que satisfazem o condicional. Na verdade retorna o dataframe completo a menos das linhas que nao satisfazem o condicional da coluna referenciada.

In [128]:
df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [129]:
df[df['W']>0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

Mais uma funcionalidade interessante, uso o condicional com uma coluna como referencia e trago os valores de outra coluna. Faço isso com um indice duplo por colchetes. Em um colchete coloco o condicional e no outro o que quero de retorno.

In [130]:
df[df['W']>0]['W']

A    2.706850
B    0.651118
D    0.188695
E    0.190794
Name: W, dtype: float64

In [132]:
df[(df['W']>0) & (df['Y']>1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [133]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [134]:
df[(df['W']>0) & (df['Y']>0)]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
E  0.190794  1.978757  2.605967  0.683509

In [135]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [136]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [137]:
col = ['RJ', 'SP','MG', 'ES','AM']

In [138]:
df['Estados'] = col

In [139]:
df

W         X         Y         Z Estados
A  2.706850  0.628133  0.907969  0.503826      RJ
B  0.651118 -0.319318 -0.848077  0.605965      SP
C -2.018168  0.740122  0.528813 -0.589001      MG
D  0.188695 -0.758872 -0.933237  0.955057      ES
E  0.190794  1.978757  2.605967  0.683509      AM

In [140]:
df.set_index('Estados')

W         X         Y         Z
Estados                                        
RJ       2.706850  0.628133  0.907969  0.503826
SP       0.651118 -0.319318 -0.848077  0.605965
MG      -2.018168  0.740122  0.528813 -0.589001
ES       0.188695 -0.758872 -0.933237  0.955057
AM       0.190794  1.978757  2.605967  0.683509

In [141]:
df

W         X         Y         Z Estados
A  2.706850  0.628133  0.907969  0.503826      RJ
B  0.651118 -0.319318 -0.848077  0.605965      SP
C -2.018168  0.740122  0.528813 -0.589001      MG
D  0.188695 -0.758872 -0.933237  0.955057      ES
E  0.190794  1.978757  2.605967  0.683509      AM

In [142]:
df.set_index('Estados',inplace=True)

In [143]:
df

W         X         Y         Z
Estados                                        
RJ       2.706850  0.628133  0.907969  0.503826
SP       0.651118 -0.319318 -0.848077  0.605965
MG      -2.018168  0.740122  0.528813 -0.589001
ES       0.188695 -0.758872 -0.933237  0.955057
AM       0.190794  1.978757  2.605967  0.683509

In [145]:
import pandas as pd

# DataFrame - Índices Multiniveis

In [163]:
outside = ['RJ', 'RJ', 'RJ','RJ']

In [164]:
inside = ['Rio de Janeiro', 'Petropolis', 'Sao Joao de Meriti', 'Nova Iguaçu']

In [165]:
indice_bolado = list(zip(outside,inside))

In [166]:
nova_variavel =  pd.MultiIndex.from_tuples(indice_bolado)

In [167]:
nova_variavel

MultiIndex([('RJ',     'Rio de Janeiro'),
            ('RJ',         'Petropolis'),
            ('RJ', 'Sao Joao de Meriti'),
            ('RJ',        'Nova Iguaçu')],
           )

In [168]:
df = pd.DataFrame(np.random.randn(4,2),index = nova_variavel)

In [169]:
df

0         1
RJ Rio de Janeiro      1.025984 -0.156598
   Petropolis         -0.031579  0.649826
   Sao Joao de Meriti  2.154846 -0.610259
   Nova Iguaçu        -0.755325 -0.346419

In [170]:
df = pd.DataFrame(np.random.randn(4,2),index = nova_variavel, columns = ['A','B'])

In [171]:
df

A         B
RJ Rio de Janeiro      0.147027 -0.479448
   Petropolis          0.558769  1.024810
   Sao Joao de Meriti -0.925874  1.862864
   Nova Iguaçu        -1.133817  0.610478

In [172]:
df.loc['RJ']

A         B
Rio de Janeiro      0.147027 -0.479448
Petropolis          0.558769  1.024810
Sao Joao de Meriti -0.925874  1.862864
Nova Iguaçu        -1.133817  0.610478

In [176]:
df.loc['RJ'].loc['Rio de Janeiro']

A    0.147027
B   -0.479448
Name: Rio de Janeiro, dtype: float64

In [177]:
df.index.names = ['Estado','Cidade']

In [178]:
df

A         B
Estado Cidade                                
RJ     Rio de Janeiro      0.147027 -0.479448
       Petropolis          0.558769  1.024810
       Sao Joao de Meriti -0.925874  1.862864
       Nova Iguaçu        -1.133817  0.610478

In [182]:
df.xs('Rio de Janeiro',level='Cidade')

A         B
Estado                    
RJ      0.147027 -0.479448

# Dados Ausentes - Data Frame

Como tratar dados ausentes?

In [183]:
d= {'A':[1,2,np.nan], 'B':[5, np.nan, np.nan], 'C':[1,2,3]}

In [184]:
df = pd.DataFrame(d)

In [185]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [186]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [187]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [188]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [189]:
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [190]:
df['A'].mean()

1.5

In [195]:
df['A'].fillna(df['A'].mean(), inplace = True)

In [196]:
;df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  1.5  NaN  3

# Group By

In [197]:
data = {'Empresa':['GOOG', 'GOOG','MSFT','MSFT','FB','FB'], 'Nome':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],'Venda':[200,120,340,124,243,350]}

In [256]:
df = pd.DataFrame(data)

TypeError: 'tuple' object is not callable

In [199]:
df

Empresa     Nome  Venda
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [201]:
group_company = df.groupby('Empresa')

In [202]:
group_company.sum()

Venda
Empresa       
FB         593
GOOG       320
MSFT       464

In [233]:
group_company.sum()

Venda
Empresa       
FB         593
GOOG       320
MSFT       464

# DataFrame - Concatenar, juntar e mesclar

In [1]:
import numpy as np
import pandas as pd

In [2]:
d = {'A':['A0','A1','A2','A3'],
                    'B':['B0','B1','B2','B3'],
                    'C':['C0','C1','C2','C3'],
                    'D':['D0','D1','D2','D3']}

In [3]:
d

{'A': ['A0', 'A1', 'A2', 'A3'],
 'B': ['B0', 'B1', 'B2', 'B3'],
 'C': ['C0', 'C1', 'C2', 'C3'],
 'D': ['D0', 'D1', 'D2', 'D3']}

In [4]:
type(d)

dict

In [5]:
df1 = None
df2 = None
df3 = None

In [6]:
df1 = pd.DataFrame(d,index=[0,1,2,3])

In [7]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [9]:
df2 = pd.DataFrame({'A':['A4','A5','A6','A7'],
                    'B':['B4','B5','B6','B7'],
                    'C':['C4','C5','C6','C7'],
                    'D':['D4','D5','D6','D7']},
                  index = [4,5,6,7])

In [10]:
df3 = pd.DataFrame({'A':['A8','A9','A10','A11'],
                    'B':['B8','B9','B10','B11'],
                    'C':['C8','C9','C10','C11'],
                    'D':['D8','D9','D10','D11']},
                  index = [8,9,10,11])

In [11]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [12]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [16]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# Operações com DataFrames

In [17]:
import pandas as pd

In [18]:
df = pd.DataFrame({'col1':[1,2,3,4], 'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']}, index = ['A','B','C','D'])

In [19]:
df

col1  col2 col3
A     1   444  abc
B     2   555  def
C     3   666  ghi
D     4   444  xyz

In [23]:
df.sum(axis=1)

A    445
B    557
C    669
D    448
dtype: int64

In [25]:
df['col1'].sum(axis=0)

10

In [26]:
df['col2'].sum(axis=0)

2109

In [27]:
df['col3'].sum(axis=0)

'abcdefghixyz'

In [30]:
df['col2'].nunique()

3

In [31]:
df['col2'].3()

444    2
555    1
666    1
Name: col2, dtype: int64

In [32]:
type(df['col2'].value_counts())

pandas.core.series.Series

In [34]:
np.array(df['col2'].value_counts().loc(''))

array(<pandas.core.indexing._LocIndexer object at 0x0000016447C12F98>,
      dtype=object)

In [43]:
df

col1  col2 col3
A     1   444  abc
B     2   555  def
C     3   666  ghi
D     4   444  xyz

Funcionalidade muito interessante:
    É possíve criar uma função e aplica-la em conjunto de dados especifico no data frame. Muito interessante para aplicar calculos diferenciados que não existam como função nativa da biblioteca pandas.

In [40]:
def quadrado(x):
    return x**2
    

In [41]:
df['col2'].apply(quadrado)

A    197136
B    308025
C    443556
D    197136
Name: col2, dtype: int64

In [44]:
df

col1  col2 col3
A     1   444  abc
B     2   555  def
C     3   666  ghi
D     4   444  xyz

In [48]:
df.loc('A','col1')

TypeError: __call__() takes from 1 to 2 positional arguments but 3 were given

In [53]:
df['A'].loc(axis=0)

KeyError: 'A'

In [54]:
df.col1[0]

1

In [57]:
type(df.col1[0]+2)

numpy.int64

# Entrada e saida de dados

In [59]:
import numpy as np
import pandas as pd

In [60]:
df = pd.read_csv('exemplo',sep=',')

In [61]:
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [62]:
df = df+1

In [63]:
df

a   b   c   d
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [64]:
df = pd.read_excel('Exemplo_Excel.xlsx', sheet_name='Sheet1')

In [65]:
df

Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [68]:
df1 = pd.read_excel('Exemplo_Excel.xlsx', sheet_name='Sheet1')

In [69]:
df1

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [72]:
df1.to_excel('Exemplo_Excel.xlsx', sheet_name='Sheet3',)

In [73]:
df_fromhtml = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [74]:
df_fromhtml

[                             Bank Name        City  ST   CERT  \
 0                   Ericson State Bank     Ericson  NE  18265   
 1     City National Bank of New Jersey      Newark  NJ  21111   
 2                        Resolute Bank      Maumee  OH  58317   
 3                Louisa Community Bank      Louisa  KY  58112   
 4                 The Enloe State Bank      Cooper  TX  10716   
 ..                                 ...         ...  ..    ...   
 555                 Superior Bank, FSB    Hinsdale  IL  32646   
 556                Malta National Bank       Malta  OH   6629   
 557    First Alliance Bank & Trust Co.  Manchester  NH  34264   
 558  National State Bank of Metropolis  Metropolis  IL   3815   
 559                   Bank of Honolulu    Honolulu  HI  21029   
 
                    Acquiring Institution       Closing Date  
 0             Farmers and Merchants Bank  February 14, 2020  
 1                        Industrial Bank   November 1, 2019  
 2               

In [75]:
type(df_fromhtml)

list

In [76]:
len(df_fromhtml)

1

In [77]:
type(df_fromhtml[0])

pandas.core.frame.DataFrame

In [78]:
data_frame_to_study = df_fromhtml[0]

In [79]:
data_frame_to_study

Bank Name        City  ST   CERT  \
0                   Ericson State Bank     Ericson  NE  18265   
1     City National Bank of New Jersey      Newark  NJ  21111   
2                        Resolute Bank      Maumee  OH  58317   
3                Louisa Community Bank      Louisa  KY  58112   
4                 The Enloe State Bank      Cooper  TX  10716   
..                                 ...         ...  ..    ...   
555                 Superior Bank, FSB    Hinsdale  IL  32646   
556                Malta National Bank       Malta  OH   6629   
557    First Alliance Bank & Trust Co.  Manchester  NH  34264   
558  National State Bank of Metropolis  Metropolis  IL   3815   
559                   Bank of Honolulu    Honolulu  HI  21029   

                   Acquiring Institution       Closing Date  
0             Farmers and Merchants Bank  February 14, 2020  
1                        Industrial Bank   November 1, 2019  
2                     Buckeye State Bank   October 25, 2019  
3      Kentucky Farmers Bank Corporation   October 25, 2019  
4                     Legend Bank, N. A.       May 31, 2019  
..                                   ...                ...  
555                Superior Federal, FSB      July 27, 2001  
556                    North Valley Bank        May 3, 2001  
557  Southern New Hampshire Bank & Trust   February 2, 2001  
558              Banterra Bank of Marion  December 14, 2000  
559                   Bank of the Orient   October 13, 2000  

[560 rows x 6 columns]

In [82]:
data_frame_to_study[(data_frame_to_study['City']=='Ericson') | (data_frame_to_study['City']=='Newark')]

Bank Name     City  ST   CERT  \
0                  Ericson State Bank  Ericson  NE  18265   
1    City National Bank of New Jersey   Newark  NJ  21111   
539               Dollar Savings Bank   Newark  NJ  31330   

          Acquiring Institution       Closing Date  
0    Farmers and Merchants Bank  February 14, 2020  
1               Industrial Bank   November 1, 2019  
539                 No Acquirer  February 14, 2004